apiVersion: batch/v1
kind: Job
metadata:
  name: media-optimizer-job
spec:
  backoffLimit: 0 # Stop retrying immediately so we can see the real error
  template:
    spec:
      containers:
      - name: media-optimizer-container
        image: media-optimizer:latest
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            # Use your actual MongoDB Atlas connection string here
            value: "mongodb://ahadn1891_db_user:<db_password>@ac-5p4aeke-shard-00-00.o2jnxwd.mongodb.net:27017,ac-5p4aeke-shard-00-01.o2jnxwd.mongodb.net:27017,ac-5p4aeke-shard-00-02.o2jnxwd.mongodb.net:27017/?ssl=true&replicaSet=atlas-1ash06-shard-0&authSource=admin&appName=mediaoptimization"
          - name: PROJECT_ROOT
            value: "/sample-assets"
        volumeMounts:
        - name: asset-volume
          mountPath: /sample-assets
      volumes:
      - name: asset-volume
        hostPath:
          path: /sample-assets
          type: Directory
      restartPolicy: Never